In [14]:
from models import GatedLinearUnit, GateAddNormNetwork 
import numpy as np
import torch

In [15]:
glu = GatedLinearUnit(input_size=5, hidden_layer_size=8, dropout_rate=0)
gan = GateAddNormNetwork(input_size=5, hidden_layer_size=8, dropout_rate=0)

In [16]:
X = np.arange(0.0, 10.0).reshape(2, 5)
X = torch.tensor(X).float()
X

tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])

In [17]:
glu(X)

tensor([[ 4.2807e-01,  2.0726e-01,  2.1990e+00,  1.6872e+00, -1.9234e-01,
         -9.8767e-01,  9.6899e-01, -4.7408e-01],
        [ 4.6298e-03,  4.4969e-02,  7.0501e+00,  3.6029e+00, -1.1065e-02,
         -4.1668e+00,  4.1393e+00, -4.9276e-02]], grad_fn=<MulBackward0>)

In [20]:
gan(X, glu(X))

tensor([[ 0.7697,  0.5426,  0.6685,  1.1049, -1.7792,  0.3328, -0.1774, -1.4620],
        [-0.8251,  1.9281, -0.3208,  0.0906, -1.0673, -0.0411,  1.1952, -0.9596]],
       grad_fn=<NativeLayerNormBackward0>)